### ISSUE TITLE
Database Research

### ISSUE THREAD

**Issue by farstarz** [farstarz/VrikshahFoundation#3]
- [x] understand the working of Firebase and its implementation

- [x] Research on what is the best structure of the database objects we will use in the project. (Focus on Events and Activities Page first)

- [ ] Research the different ways we can display this information to the client.

**Comment by lynntfuzz** [comment]
- Authentication
- Event object
- Interface for front end- addEvent() editEvent() removeEvent() findAllEvents() 
OR User---> Event association. How to save id of google api calendar.
